# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdebv_fun',
                'doc_host': 'https://Mariyselita.github.io',
                'git_url': 'https://github.com/Mariyselita/nbdebv_fun',
                'lib_path': 'nbdebv_fun'},
  'syms': {'nbdebv_fun\\core': {'nbdebv_fun\\core.foo': ('core.html#foo', 'nbdebv_fun\\core.py')}}}