name: Deploy to GitHub Pages
on: [workflow_dispatch, pull_request, push]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Asegúrate de usar la versión de Python que necesitas

      - name: Install Dependencies and create documentation
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -Uq git+https://github.com/fastai/ghapi.git
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.deb
          sudo dpkg -i quarto-1.2.313-linux-amd64.deb
          pip install -Uq matplotlib
          pip install -Uq setuptools
          pip install -Uq seaborn
          pip install -Uq scikit-learn
          pip install -Uq shapely
          pip install -Uq pandas
          pip install -Uq numpy
          nbdev_docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_docs
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
